//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by chitem.rc
//
#define IDC_CHECKSTORE                  3
#define IDC_CHECKSPELL                  4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CHITEM_DIALOG               102
#define IDS_FILENAME                    102
#define IDS_OPENFILE                    103
#define IDS_RESCAN                      104
#define IDS_RESCAN2                     105
#define IDS_OPTIONS                     106
#define IDS_RUN                         107
#define IDS_EXIT                        108
#define IDS_EVENT                       109
#define IDS_RUN2                        110
#define IDS_RUN3                        111
#define IDS_RUN4                        112
#define IDD_ITEMGENERAL                 113
#define IDS_FIND1                       113
#define IDD_ITEMICONS                   114
#define IDS_FIND2                       114
#define IDD_ITEMDESC                    115
#define IDS_FIND3                       115
#define IDD_ITEMUSE                     116
#define IDS_FIND4                       116
#define IDD_ITEMEQUIP                   117
#define IDS_CFBHELP                     117
#define IDD_ITEMEFFECT                  118
#define IDS_CFBOPEN                     118
#define IDS_GAMEOPT                     119
#define IDS_FINDSTOR                    120
#define IDS_FINDSCRIPT                  121
#define IDS_FINDDLG                     122
#define IDS_FINDPROJ                    123
#define IDS_CHECKCRE                    124
#define IDS_CHECKSCRIPT                 125
#define IDS_CHECKDLG                    126
#define IDS_CHECKEFF                    127
#define IDR_MAINFRAME                   128
#define IDS_CANCEL                      128
#define IDD_CHECK                       129
#define IDS_LOAD                        129
#define IDS_ANIMATION                   130
#define IDB_GETFILES                    131
#define IDR_MENUBAR                     131
#define IDD_FINDITEM                    131
#define IDS_LOADEX                      131
#define IDD_ITEMEDIT                    132
#define IDR_BAMMENU                     132
#define IDS_SAVE                        132
#define IDS_INVBAM                      133
#define IDR_TREEMENU                    133
#define IDD_EXTRACT                     134
#define IDS_SAVEORDER                   134
#define IDD_PROGRESS                    135
#define IDS_XPOS                        135
#define IDD_ITEMPICKER                  136
#define IDS_YPOS                        136
#define IDD_VVCEDIT                     137
#define IDS_COMPRESSED                  137
#define IDD_CFB                         138
#define IDS_RLE                         138
#define IDD_STOREEDIT                   139
#define IDS_XSIZE                       139
#define IDD_STOREGENERAL                140
#define IDS_YSIZE                       140
#define IDD_STOREITEMS                  141
#define IDS_FRAME                       141
#define IDD_EFFEDIT                     142
#define IDS_CYCLE                       142
#define IDD_VARIABLES                   143
#define IDS_FINC                        143
#define IDD_STORERENTAL                 144
#define IDS_DSIZE                       144
#define IDD_COMPAT                      145
#define IDS_PLAY                        145
#define IDS_ITEM                        146
#define IDD_ITEMEXTRA                   147
#define IDS_SPELL                       147
#define IDD_STOREEXTRA                  148
#define IDS_CREATURE                    148
#define IDD_BAMEDIT                     149
#define IDS_STORE                       149
#define IDD_PALETTE                     150
#define IDS_AREA                        150
#define IDD_SPELLGENERAL                151
#define IDS_VVC                         151
#define IDS_BITMAP                      152
#define IDD_EXTRACT2                    153
#define IDS_PRO                         153
#define IDS_RESCAN3                     154
#define IDD_SPELLEQUIP                  155
#define IDS_RESCAN4                     155
#define IDS_DBLCLICKLEAF                156
#define IDD_SPELLEXTRA                  157
#define IDS_RESCAN5                     157
#define IDD_SPELLDESC                   158
#define IDS_NEW                         158
#define IDD_SPELLEFFECT                 159
#define IDS_EFFECT                      159
#define IDS_ORDER                       160
#define IDD_SPELLEDIT                   160
#define IDD_AREAGENERAL                 161
#define IDS_WMP                         161
#define IDD_AREAEDIT                    162
#define IDS_MOS                         162
#define IDD_AREAACTOR                   163
#define IDS_2DA                         163
#define IDD_SCHEDULE                    164
#define IDS_IDS                         164
#define IDD_PROJEDIT                    165
#define IDS_DIALOG                      165
#define IDD_AREAENTRANCE                166
#define IDS_GAME                        166
#define IDD_AREATRIGGER                 167
#define IDS_CHECK                       167
#define IDD_AREASPAWN                   168
#define IDR_SHORTCUT                    168
#define IDS_MUS                         168
#define IDD_CREATUREEDIT                169
#define IDS_SCRIPT                      169
#define IDD_CREATUREGENERAL             170
#define IDS_MUSIC                       170
#define IDD_CREATUREICONS               171
#define IDS_WED                         171
#define IDD_CREATURESKILLS              172
#define IDS_CHU                         172
#define IDD_CREATURERES                 173
#define IDS_WAV                         173
#define IDD_CREATURESTRINGS             174
#define IDS_TILESET                     174
#define IDD_CREATUREUNKNOWN             175
#define IDS_UNKNOWN                     175
#define IDD_AREASONGS                   176
#define IDS_MOVIE                       176
#define IDD_AREAAMBIENT                 177
#define IDS_WFX                         177
#define IDD_AREAINT                     178
#define IDS_SRC                         178
#define IDD_AREACONTAINER               179
#define IDS_IAP                         179
#define IDD_AREADOOR                    180
#define IDS_CFBFOLDER                   180
#define IDD_AREAVARIABLE                181
#define IDS_SAVEBACK                    181
#define IDD_DIALOGEDIT                  182
#define IDS_WEIDU                       182
#define IDD_SEARCHNODE                  183
#define IDS_EDIT                        183
#define IDD_ADDLINK                     184
#define IDS_ADDSETUP                    184
#define IDD_PROJEXT                     185
#define IDS_REMOVESETUP                 185
#define IDD_GAMEEDIT                    186
#define IDS_OPENEFFECT                  186
#define IDD_MAPEDIT                     187
#define IDS_OPENCHITIN                  187
#define IDD_MAPLINK                     188
#define IDS_RIGHT                       188
#define IDD_CREATUREITEMS               189
#define IDS_GAMETYPE                    189
#define IDD_MOSEDIT                     190
#define IDS_DIALOGF                     190
#define IDD_WEIDU                       191
#define IDS_PSTVAR                      191
#define IDD_IMAGEVIEW                   192
#define IDS_DLG30                       192
#define IDS_BG1AREA                     193
#define IDD_2DAEDIT                     194
#define IDS_IWD2                        194
#define IDD_IDSEDIT                     195
#define IDS_UNLIMIT                     195
#define IDD_EDIT                        196
#define IDS_NOZIP                       196
#define IDD_IAPDIALOG                   197
#define IDS_WEAPON                      197
#define IDD_COLORPICKER                 198
#define IDS_XPLIST                      198
#define IDD_AREAANIM                    199
#define IDS_DLTC                        199
#define IDD_SCRIPTEDIT                  200
#define IDS_LOGTYPE                     200
#define IDD_SHOWLOG                     201
#define IDS_TOOLTIP                     201
#define IDR_SCRIPT                      202
#define IDD_STRREFDLG                   202
#define IDS_PROGRESS                    202
#define IDR_ITEM                        203
#define IDD_SAVHANDLE                   203
#define IDS_READONLY                    203
#define IDR_SPELL                       204
#define IDD_PANICBUTTON                 204
#define IDS_SETUPNAME                   204
#define IDR_STORE                       205
#define IDD_MUSEDIT                     205
#define IDS_SAVEBACK2                   205
#define IDR_EFFECT                      206
#define IDD_CREATUREEFF                 206
#define IDS_BIFLIST                     206
#define IDR_AREA                        207
#define IDD_WEDEDIT                     207
#define IDS_FILELIST                    207
#define IDR_CREATURE                    208
#define IDD_WEDPOLY                     208
#define IDS_PLT                         208
#define IDR_WORLDMAP                    209
#define IDD_MASSCLEAR                   209
#define IDS_BIF                         209
#define IDR_GAME                        210
#define IDS_FILEMASK                    210
#define IDR_TLKMENU                     211
#define IDS_FILEEXT                     211
#define IDR_VVC                         212
#define IDS_OVERRIDE                    212
#define IDR_PROJECT                     213
#define IDD_TISDIALOG                   213
#define IDS_EXTRACT                     213
#define IDD_KEYEDIT                     214
#define IDR_2DA                         214
#define IDS_SEARCH                      214
#define IDR_IDS                         215
#define IDD_WEDTILE                     215
#define IDS_DROPFRAME                   215
#define IDR_MUSIC                       216
#define IDD_SPELLTOOL                   216
#define IDS_NEWFRAME                    216
#define IDR_TILE                        217
#define IDS_MULTIFRAME                  217
#define IDD_CHUIEDIT                    217
#define IDS_DROPCYCLE                   218
#define IDR_CHUI                        218
#define IDD_SRCEDIT                     218
#define IDS_NEWCYCLE                    219
#define IDR_SRC                         219
#define IDD_AREAMAP                     219
#define IDS_PAPERDOLL                   220
#define IDD_STOREDRINKS                 220
#define IDR_WEDMENU                     220
#define IDS_CENTER                      221
#define IDD_POLYGON                     221
#define IDR_CHITIN                      221
#define IDS_CLEANUP                     222
#define IDD_TEXTVIEW                    222
#define IDS_TRANSPARENT                 223
#define IDD_CREATUREPST                 223
#define IDS_FRAME2                      224
#define IDD_GAMESTATS                   224
#define IDS_ADDFRAME                    225
#define IDD_GAMEGENERAL                 225
#define IDS_SETFRAME                    226
#define IDD_GAMEPCINFO                  226
#define IDS_DELFRAME                    227
#define IDD_CREATUREIWD                 227
#define IDS_CENTERFRAME                 228
#define IDD_AREATRIGGERSTRINGS          228
#define IDS_BAM                         229
#define IDD_CREATUREIWD2                229
#define IDS_FRAME15                     230
#define IDD_CREATUREOVR                 230
#define IDS_VVCFLAG                     231
#define IDD_ANIMDIALOG                  231
#define IDS_SEQFLAG                     232
#define IDD_CREATURELEVELS              232
#define IDS_MINIMAP                     233
#define IDD_AREAPROJ                    233
#define IDS_TISEXTRACT                  234
#define IDD_PROJGEMRB                   234
#define IDS_OVERLAY                     235
#define IDD_PROJAREAGEMRB               235
#define IDS_VEF                         236
#define IDS_INI                         237
#define IDS_FEATURE                     238
#define IDS_DESC                        239
#define IDS_TARGET                      240
#define IDS_DURATION                    241
#define IDS_TIMING                      242
#define IDS_TEXT                        243
#define IDS_TEXT2                       244
#define IDS_PDAMAGE                     245
#define IDS_PIDS                        246
#define IDS_PCOLOR                      247
#define IDS_UNDEFINED                   248
#define IDS_PAR3                        249
#define IDS_VARNAME                     250
#define IDS_SOURCE                      251
#define IDS_SECTYPE                     252
#define IDS_SCHOOL                      253
#define IDS_RESOURCE                    254
#define IDS_RESOURCE2                   255
#define IDS_RESOURCE3                   256
#define IDS_RESIST                      257
#define IDS_STHROW                      258
#define IDS_SBONUS                      259
#define IDS_POWER                       260
#define IDS_DIE                         261
#define IDS_ROLL                        262
#define IDS_PARAM1                      263
#define IDS_PARAM2                      264
#define IDS_PROB1                       265
#define IDS_PROB2                       266
#define IDS_TOB                         267
#define IDS_DELOVER                     268
#define IDS_TILES                       269
#define IDS_2C                          270
#define IDS_VISIBLE                     271
#define IDS_FIELDS                      272
#define IDS_LABEL                       273
#define IDS_EXPIRATION                  274
#define IDS_AVISIBLE                    275
#define IDS_ABLEND                      276
#define IDS_ANOLIGHT                    277
#define IDS_APARTIAL                    278
#define IDS_ASYNC                       279
#define IDS_ANOWALL                     280
#define IDS_AFOG                        281
#define IDS_ATRANSP                     282
#define IDS_AALL                        283
#define IDS_APALETTE                    284
#define IDS_AMIRROR                     285
#define IDS_ACOMBAT                     286
#define IDS_CHANCE                      287
#define IDS_GROUND                      288
#define IDC_RESCAN                      1000
#define IDC_RESCAN2                     1001
#define IDC_ICONCHK                     1002
#define IDC_FILENAME                    1003
#define IDC_ITEMREF                     1004
#define IDC_RESCAN3                     1005
#define IDC_OPENFILE                    1006
#define IDC_STRREF                      1007
#define IDC_RESCAN4                     1008
#define IDC_ATTR                        1009
#define IDC_RESCAN5                     1010
#define IDC_DLGCHK                      1011
#define IDC_EXTHEAD                     1012
#define IDC_ADDITEM                     1013
#define IDC_USABILITY                   1014
#define IDC_DELITEM                     1015
#define IDC_OPTIONS                     1016
#define IDC_ITEMTYPE                    1017
#define IDC_SAVE                        1018
#define IDC_COMPAT                      1019
#define IDC_ALLSET                      1020
#define IDC_OPTIONS2                    1021
#define IDC_MPLUS                       1022
#define IDC_VERSION                     1023
#define IDC_OPTIONS1                    1024
#define IDC_EVENT                       1025
#define IDC_ALLUNSET                    1026
#define IDC_WPROF                       1027
#define IDC_NOCHITIN                    1028
#define IDC_STATR                       1029
#define IDC_OTHER                       1030
#define IDC_ANIM                        1031
#define IDC_WARN                        1032
#define IDC_NOSPEC                      1033
#define IDC_SKIPEXT                     1034
#define IDC_SOA                         1035
#define IDC_EVENT_TYPE                  1036
#define IDC_DUPLO                       1037
#define IDC_SCRIPT                      1038
#define IDC_CHECKPROJ                   1039
#define IDC_MISSING                     1040
#define IDC_FINDPROJ                    1041
#define IDC_FINDITEM                    1042
#define IDC_MPROJ                       1043
#define IDC_FINDSPELL                   1044
#define IDC_PROJ                        1045
#define IDC_PROJ2                       1046
#define IDC_MTYPE                       1047
#define IDC_ITEMTYPE2                   1048
#define IDC_EFFECT                      1049
#define IDC_EFFECT2                     1050
#define IDC_MFEAT                       1051
#define IDC_PROGRESS                    1052
#define IDC_FINDEFF                     1053
#define IDC_MRES                        1054
#define IDC_RESOURCE                    1055
#define IDC_CHECKEFF                    1056
#define IDC_FINDCRE                     1057
#define IDC_ITEMNAME                    1058
#define IDC_VVC                         1059
#define IDC_RESOURCE3                   1060
#define IDC_LONGNAME                    1061
#define IDC_CHECKCRE                    1062
#define IDC_SAVEAS                      1063
#define IDC_MEA                         1064
#define IDC_LOADEX                      1065
#define IDC_EXTADD                      1066
#define IDC_MGENERAL                    1067
#define IDC_FINDDIALOG                  1068
#define IDC_ICENTER                     1069
#define IDC_DAWN                        1070
#define IDC_RGB                         1071
#define IDC_SHORTNAME                   1072
#define IDC_EXTEFFADD                   1073
#define IDC_MRACE                       1074
#define IDC_ADDITEM2                    1075
#define IDC_CHECKDIALOG                 1076
#define IDC_GCENTER                     1077
#define IDC_REMOVE2                     1078
#define IDC_SHORTDESC                   1079
#define IDC_MCLASS                      1080
#define IDC_STRREF2                     1081
#define IDC_LONGDESC                    1082
#define IDC_MSPECIFIC                   1083
#define IDC_MGENDER                     1084
#define IDC_SHORTREF                    1085
#define IDC_MALIGN                      1086
#define IDC_LONGREF                     1087
#define IDC_MVAR                        1088
#define IDC_REMOVE                      1089
#define IDC_SHORTDESCREF                1090
#define IDC_LONGDESCREF                 1091
#define IDC_LOAD                        1092
#define IDC_PAR_UNDEFINED               1093
#define IDC_DESTX                       1094
#define IDC_PAR_COLOR                   1095
#define IDC_VALUE                       1096
#define IDC_PICK                        1097
#define IDC_EXTHEADNUM                  1098
#define IDC_X25                         1099
#define IDC_FILEMASK                    1100
#define IDC_CONV                        1101
#define IDC_DESCPATH                    1102
#define IDC_BAM2                        1103
#define IDC_DESCRIPTION                 1104
#define IDC_EA                          1105
#define IDC_STORENAMEREF                1106
#define IDC_PEASANTPRICE                1107
#define IDC_XPOS                        1108
#define IDC_XPOS2                       1109
#define IDC_WAV                         1110
#define IDC_WED                         1111
#define IDC_POSX                        1112
#define IDC_EXTREMOVE                   1113
#define IDC_ITEMGRNDICON                1114
#define IDC_X33                         1115
#define IDC_EA2                         1116
#define IDC_PAR_IDS                     1117
#define IDC_POSY                        1118
#define IDC_BAM3                        1119
#define IDC_BAM4                        1120
#define IDC_BAM5                        1121
#define IDC_VALUE2                      1122
#define IDC_EXTCOPY                     1123
#define IDC_ITEMDESCICON                1124
#define IDC_X27                         1125
#define IDC_GENERAL                     1126
#define IDC_PAR_DAMAGE                  1127
#define IDC_PAR_SPECIAL                 1128
#define IDC_GENERAL2                    1129
#define IDC_VARNAME                     1130
#define IDC_DESTY                       1131
#define IDC_EXTEFFNUM                   1132
#define IDC_RACE                        1133
#define IDC_VARNAME2                    1134
#define IDC_MAGICLEVEL                  1135
#define IDC_MINLEVEL                    1136
#define IDC_MINSTR                      1137
#define IDC_MININT                      1138
#define IDC_MINDEX                      1139
#define IDC_MINWIS                      1140
#define IDC_MINCHA                      1141
#define IDC_MINSTRBONUS                 1142
#define IDC_MINCON                      1143
#define IDC_FLAGS                       1144
#define IDC_COLD                        1145
#define IDC_SILVER                      1146
#define IDC_TWOHAND                     1147
#define IDC_DISPLAYABLE                 1148
#define IDC_COPYABLE                    1149
#define IDC_BOW                         1150
#define IDC_CONVERSIBLE                 1151
#define IDC_EXTTYPE                     1152
#define IDC_RANGE                       1153
#define IDC_FLAG1                       1154
#define IDC_FLAG2                       1155
#define IDC_FLAG3                       1156
#define IDC_FLAG4                       1157
#define IDC_FLAG5                       1158
#define IDC_FLAG6                       1159
#define IDC_FLAG7                       1160
#define IDC_FLAG8                       1161
#define IDC_FLAG9                       1162
#define IDC_FLAG10                      1163
#define IDC_FLAG11                      1164
#define IDC_FLAG12                      1165
#define IDC_FLAG13                      1166
#define IDC_FLAG14                      1167
#define IDC_FLAG15                      1168
#define IDC_FLAG16                      1169
#define IDC_FLAG17                      1170
#define IDC_FLAG18                      1171
#define IDC_FLAG19                      1172
#define IDC_FLAG20                      1173
#define IDC_FLAG21                      1174
#define IDC_FLAG22                      1175
#define IDC_CONVREF                     1176
#define IDC_FLAG23                      1176
#define IDC_DURATIONLABEL               1177
#define IDC_THAC0                       1178
#define IDC_ROLL                        1179
#define IDC_DIE                         1180
#define IDC_ADD                         1181
#define IDC_ADD2                        1182
#define IDC_EFFNUM                      1183
#define IDC_ADD3                        1184
#define IDC_HEADNUM                     1185
#define IDC_CHARGES                     1186
#define IDC_ROLL2                       1187
#define IDC_STRBONUS                    1188
#define IDC_DIE2                        1189
#define IDC_PROJID                      1190
#define IDC_ANIM1                       1191
#define IDC_ANIM2                       1192
#define IDC_ANIM3                       1193
#define IDC_PERDAY                      1194
#define IDC_XBOW                        1195
#define IDC_MISC                        1196
#define IDC_DIVINER                     1197
#define IDC_ENCHANTER                   1198
#define IDC_ILLUSIONIST                 1199
#define IDC_INVOKER                     1200
#define IDC_TRANSMUTER                  1201
#define IDC_NECROMANCER                 1202
#define IDC_BASECLASS                   1203
#define IDC_FERLAIN                     1204
#define IDC_BERSERKER                   1205
#define IDC_WIZARDSLAYER                1206
#define IDC_KENSAI                      1207
#define IDC_CAVALIER                    1208
#define IDC_INQUISITOR                  1209
#define IDC_UNDEADHUNTER                1210
#define IDC_ABJURER                     1211
#define IDC_CONJURER                    1212
#define IDC_POWER                       1213
#define IDC_SAVETYPE                    1214
#define IDC_SAVEBONUS                   1215
#define IDC_PROB1                       1216
#define IDC_PROB2                       1217
#define IDC_UNKNOWN40                   1218
#define IDC_CUREPRICE                   1219
#define IDC_UNKNOWN42                   1220
#define IDC_PRICECHANGE                 1221
#define IDC_SPEED                       1222
#define IDC_UNKNOWN50                   1223
#define IDC_EFFTARGET                   1224
#define IDC_UNKNOWN154                  1225
#define IDC_EXPLODE1                    1226
#define IDC_EXPLODE2                    1227
#define IDC_SHORTNAMETAG                1228
#define IDC_LONGNAMETAG                 1229
#define IDC_SHORTDESCTAG                1230
#define IDC_LONGDESCTAG                 1231
#define IDC_TLKCHANGE                   1232
#define IDC_UNKNOWN                     1233
#define IDC_OVERRIDE                    1234
#define IDC_FILETYPE                    1235
#define IDC_BIFNAME                     1236
#define IDC_FEATURE                     1237
#define IDC_UNKNOWN1                    1238
#define IDC_BATTLE                      1239
#define IDC_UNKNOWN3                    1240
#define IDC_RESIST                      1241
#define IDC_EQUIPREMOVE                 1242
#define IDC_EQUIPADD                    1243
#define IDC_EQUIPCOPY                   1244
#define IDC_EQUIPPASTE                  1245
#define IDC_UNKNOWN1C                   1246
#define IDC_EQUIPNUM                    1247
#define IDC_DAMAGETYPE                  1248
#define IDC_REMOVE3                     1249
#define IDC_EFFOPCODE                   1250
#define IDC_EFFOPCODE2                  1251
#define IDC_DESCOPEN                    1252
#define IDC_UNKNOWN4                    1253
#define IDC_PARLABEL1                   1254
#define IDC_UNKNOWN5                    1255
#define IDC_PARLABEL2                   1256
#define IDC_UNKNOWN6                    1257
#define IDC_EXTUSEICON                  1258
#define IDC_UNKNOWN7                    1259
#define IDC_USEICON                     1260
#define IDC_UNKNOWN8                    1261
#define IDC_UNKNOWN9                    1262
#define IDC_FRAMERATE                   1263
#define IDC_UNKNOWN38                   1264
#define IDC_UNKNOWN3C                   1265
#define IDC_UNKNOWN44                   1266
#define IDC_UNKNOWN48                   1267
#define IDC_XCO                         1268
#define IDC_YCO                         1269
#define IDC_UNKNOWN5C                   1270
#define IDC_ZCO                         1271
#define IDC_SOUND1                      1272
#define IDC_SOUND2                      1273
#define IDC_UNKNOWN24                   1274
#define IDC_SOUND3                      1275
#define IDC_UNKNOWN30                   1276
#define IDC_BAM1                        1277
#define IDC_SEQ1                        1278
#define IDC_UNKNOWN4C                   1279
#define IDC_UNKNOWN74                   1280
#define IDC_2DACHANGE                   1281
#define IDC_UNKNOWN88                   1282
#define IDC_SPELLREF                    1283
#define IDC_CREREF                      1284
#define IDC_STOREREF                    1285
#define IDC_VARIABLE                    1286
#define IDC_STRUCT                      1287
#define IDC_SKIPDVAR                    1288
#define IDC_VTYPE                       1289
#define IDC_RADIO2                      1290
#define IDC_RADIO3                      1291
#define IDC_VARPICKER                   1292
#define IDC_LOOP                        1293
#define IDC_SEQUENCING                  1294
#define IDC_VARIABLES                   1295
#define IDC_ALLOWEDITEMS                1296
#define IDC_REMOVEITEM                  1297
#define IDC_STOREDITEMS                 1298
#define IDC_REMOVEITEM2                 1299
#define IDC_SPELLS                      1300
#define IDC_REMOVESPELL                 1301
#define IDC_ADDSPELL                    1302
#define IDC_DRINKS                      1303
#define IDC_REMOVEDRINK                 1304
#define IDC_ADDDRINK                    1305
#define IDC_DRINKNAMEREF                1306
#define IDC_DRINKRESREF                 1307
#define IDC_SPELLRESREF                 1308
#define IDC_DRINKSTRENGTH               1309
#define IDC_DRINKPRICE                  1310
#define IDC_DRINKNAME                   1311
#define IDC_CUREDESCREF                 1312
#define IDC_CURENAME                    1313
#define IDC_USE1                        1314
#define IDC_USE2                        1315
#define IDC_USE3                        1316
#define IDC_COUNT                       1317
#define IDC_COUNT2                      1318
#define IDC_STORETYPE                   1319
#define IDC_STORENAME                   1320
#define IDC_BUYING                      1321
#define IDC_STEALING                    1322
#define IDC_SELLINGPERCENT              1323
#define IDC_BUYINGPERCENT               1324
#define IDC_STEALPERCENT                1325
#define IDC_SELLING                     1326
#define IDC_CURES                       1327
#define IDC_DONATE                      1328
#define IDC_CAPACITY                    1329
#define IDC_IDPRICE                     1330
#define IDC_FENCED                      1331
#define IDC_UNKNOWN10                   1332
#define IDC_UNKNOWN54                   1333
#define IDC_UNKNOWN60                   1334
#define IDC_UNKNOWN70                   1335
#define IDC_UNKNOWN64                   1336
#define IDC_UNKNOWN58                   1337
#define IDC_RUMOURRES                   1338
#define IDC_NOBLEPRICE                  1339
#define IDC_ROYALPRICE                  1340
#define IDC_PEASANT                     1341
#define IDC_MERCHANT                    1342
#define IDC_NOBLE                       1343
#define IDC_ROYAL                       1344
#define IDC_MERCHANTPRICE               1345
#define IDC_ICONRES                     1346
#define IDC_U1                          1347
#define IDC_U2                          1348
#define IDC_U3                          1349
#define IDC_U4                          1350
#define IDC_U5                          1351
#define IDC_U6                          1352
#define IDC_U7                          1353
#define IDC_U8                          1354
#define IDC_U9                          1355
#define IDC_U10                         1356
#define IDC_U11                         1357
#define IDC_U12                         1358
#define IDC_U13                         1359
#define IDC_U14                         1360
#define IDC_U15                         1361
#define IDC_U16                         1362
#define IDC_U17                         1363
#define IDC_U18                         1364
#define IDC_U19                         1365
#define IDC_U20                         1366
#define IDC_U21                         1367
#define IDC_U22                         1368
#define IDC_U23                         1369
#define IDC_U24                         1370
#define IDC_U25                         1371
#define IDC_U26                         1372
#define IDC_U27                         1373
#define IDC_U28                         1374
#define IDC_U29                         1375
#define IDC_U30                         1376
#define IDC_U31                         1377
#define IDC_U32                         1378
#define IDC_U33                         1379
#define IDC_U34                         1380
#define IDC_U35                         1381
#define IDC_U36                         1382
#define IDC_U37                         1383
#define IDC_U38                         1384
#define IDC_U39                         1385
#define IDC_U40                         1386
#define IDC_UBYTES                      1387
#define IDC_PSTVAR                      1388
#define IDC_DLG30                       1389
#define IDC_SETUPNAME                   1390
#define IDC_GAMETYPE                    1391
#define IDC_FINDSCRIPT                  1392
#define IDC_IWD2                        1393
#define IDC_CHECKSCRIPT                 1394
#define IDC_BG1AREA                     1395
#define IDC_FINDSTORE                   1396
#define IDC_CHECKITEM                   1397
#define IDC_LOGTYPE                     1398
#define IDC_TOOLTIP                     1399
#define IDC_READONLY                    1400
#define IDC_CLEARALL                    1401
#define IDC_ITEMRES                     1402
#define IDC_REMALLITEM                  1403
#define IDC_LOADSCREEN                  1404
#define IDC_COMPRESSED                  1405
#define IDC_XSIZE                       1406
#define IDC_YSIZE                       1407
#define IDC_FRAME                       1408
#define IDC_CYCLE                       1409
#define IDC_NOZIP                       1410
#define IDC_DCENTER                     1411
#define IDC_BAMFRAME1                   1412
#define IDC_BAMFRAME2                   1413
#define IDC_YPOS                        1414
#define IDC_YPOS2                       1415
#define IDC_CYCFRAME                    1416
#define IDC_RLE                         1417
#define IDC_PLAY                        1418
#define IDC_BAMFRAME3                   1419
#define IDC_BAMFRAME4                   1420
#define IDC_BAMFRAME5                   1421
#define IDC_BACKGROUND                  1422
#define IDC_BAMFRAME6                   1423
#define IDC_SAVEORDER                   1424
#define IDC_SMOOTH                      1425
#define IDC_PAPERDOLL                   1426
#define IDC_ORDER                       1427
#define IDC_PLAY1                       1428
#define IDC_SCHEDULE                    1429
#define IDC_NIGHT                       1430
#define IDC_RECALCBOX                   1431
#define IDC_SPELLTYPEPICKER             1432
#define IDC_SECTYPE                     1433
#define IDC_ATTR1                       1434
#define IDC_ATTR2                       1435
#define IDC_ATTR3                       1436
#define IDC_ATTR4                       1437
#define IDC_ATTR5                       1438
#define IDC_ATTR6                       1439
#define IDC_ATTR7                       1440
#define IDC_ATTR8                       1441
#define IDC_ATTR9                       1442
#define IDC_ATTR10                      1443
#define IDC_ATTR11                      1444
#define IDC_ATTR12                      1445
#define IDC_ATTR13                      1446
#define IDC_ATTR14                      1447
#define IDC_ATTR15                      1448
#define IDC_ATTR16                      1449
#define IDC_PLAY2                       1450
#define IDC_BOOKICON                    1451
#define IDC_LEVEL                       1452
#define IDC_GREEN                       1453
#define IDC_TEXT                        1454
#define IDC_PLAY3                       1455
#define IDC_SCHOOL                      1456
#define IDC_PRIESTTYPE                  1457
#define IDC_EXCLUDE                     1458
#define IDC_SELECTION                   1459
#define IDC_UNKNOWN0C                   1460
#define IDC_SELECTION2                  1461
#define IDC_UNKNOWN28                   1462
#define IDC_UNKNOWN2C                   1463
#define IDC_UNKNOWN2A                   1464
#define IDC_BLUE                        1465
#define IDC_BLUE2                       1466
#define IDC_BYTE34                      1467
#define IDC_IDX                         1468
#define IDC_RESOLVE                     1469
#define IDC_REPLACE                     1470
#define IDC_CHANGE                      1471
#define IDC_NEWVALUE                    1472
#define IDC_TO                          1473
#define IDC_FROM                        1474
#define IDC_UNKNOWN16                   1475
#define IDC_UNKNOWN22                   1476
#define IDC_UNKNOWN1A                   1477
#define IDC_TARGETNUM                   1478
#define IDC_WEAPON                      1479
#define IDC_NORTHRES                    1480
#define IDC_U48                         1481
#define IDC_SOUTHRES                    1482
#define IDC_ACTORPICKER                 1483
#define IDC_WESTRES                     1484
#define IDC_VISIBLE                     1485
#define IDC_EASTRES                     1486
#define IDC_U2C                         1487
#define IDC_NORTHFLAG                   1488
#define IDC_WESTFLAG                    1489
#define IDC_FACE                        1490
#define IDC_SOUTHFLAG                   1491
#define IDC_EASTFLAG                    1492
#define IDC_HOUR1                       1493
#define IDC_HOUR2                       1494
#define IDC_HOUR3                       1495
#define IDC_HOUR4                       1496
#define IDC_HOUR5                       1497
#define IDC_HOUR6                       1498
#define IDC_HOUR7                       1499
#define IDC_HOUR8                       1500
#define IDC_HOUR9                       1501
#define IDC_HOUR10                      1502
#define IDC_HOUR11                      1503
#define IDC_HOUR12                      1504
#define IDC_HOUR13                      1505
#define IDC_HOUR14                      1506
#define IDC_HOUR15                      1507
#define IDC_HOUR16                      1508
#define IDC_HOUR17                      1509
#define IDC_HOUR18                      1510
#define IDC_HOUR19                      1511
#define IDC_HOUR20                      1512
#define IDC_HOUR21                      1513
#define IDC_HOUR22                      1514
#define IDC_HOUR23                      1515
#define IDC_HOUR24                      1516
#define IDC_DAY                         1517
#define IDC_ALL                         1518
#define IDC_TWILIGHT                    1519
#define IDC_NONE                        1520
#define IDC_FUNCTION                    1521
#define IDC_KEEPGRAY                    1522
#define IDC_PAR1B1                      1523
#define IDC_PAR1B2                      1524
#define IDC_PAR1B3                      1525
#define IDC_PAR1B4                      1526
#define IDC_PAR2B1                      1527
#define IDC_PAR2B2                      1528
#define IDC_PAR2B3                      1529
#define IDC_PAR2B4                      1530
#define IDC_BYTE1                       1531
#define IDC_POS2X                       1532
#define IDC_POS1X                       1533
#define IDC_POS1Y                       1534
#define IDC_POS2Y                       1535
#define IDC_TPOSX                       1536
#define IDC_UNKNOWN23                   1537
#define IDC_UNLIMITED                   1538
#define IDC_LOAD2                       1539
#define IDC_CURSORIDX                   1540
#define IDC_CURSOR                      1541
#define IDC_DESTAREA                    1542
#define IDC_TPOSY                       1543
#define IDC_ENTRANCENAME                1544
#define IDC_POS1X2                      1545
#define IDC_PARTY                       1546
#define IDC_DETECT                      1547
#define IDC_JOINABLE                    1548
#define IDC_REMOVAL                     1549
#define IDC_TRAPPED                     1550
#define IDC_DETECTED                    1551
#define IDC_KEY                         1552
#define IDC_POS1Y2                      1553
#define IDC_POS2X2                      1554
#define IDC_POS2Y2                      1555
#define IDC_LONGNAMEREF                 1556
#define IDC_LOCKED                      1557
#define IDC_EXTPASTE                    1558
#define IDC_SHORTNAMEREF                1559
#define IDC_XPVALUE                     1560
#define IDC_CURRXP                      1561
#define IDC_GOLD                        1562
#define IDC_STATEFLAGS                  1563
#define IDC_DUALFLAGS                   1564
#define IDC_CURRHP                      1565
#define IDC_MAXHP                       1566
#define IDC_SMALLPORTRAIT               1567
#define IDC_LARGEPORTRAIT               1568
#define IDC_SMALLPORTRAITICON           1569
#define IDC_LARGEPORTRAITICON           1570
#define IDC_CMETAL                      1571
#define IDC_CMINOR                      1572
#define IDC_CMAJOR                      1573
#define IDC_CSKIN                       1574
#define IDC_CLEATHER                    1575
#define IDC_CARMOR                      1576
#define IDC_CHAIR                       1577
#define IDC_LEVEL1                      1578
#define IDC_LEVEL2                      1579
#define IDC_LEVEL3                      1580
#define IDC_IDSEA                       1581
#define IDC_IDSGENERAL                  1582
#define IDC_IDSRACE                     1583
#define IDC_IDSALIGNMENT                1584
#define IDC_IDSCLASS                    1585
#define IDC_IDSSPECIFIC                 1586
#define IDC_SONG                        1587
#define IDC_REST                        1588
#define IDC_ENTRANCEPICKER              1589
#define IDC_REGIONTYPE                  1590
#define IDC_HATED                       1591
#define IDC_IDSGENDER                   1592
#define IDC_MORALE                      1593
#define IDC_MBREAK                      1594
#define IDC_MRECOVERY                   1595
#define IDC_HIDE                        1596
#define IDC_DETILL                      1597
#define IDC_SETTRAP                     1598
#define IDC_LOCKPICK                    1599
#define IDC_STEALTH                     1600
#define IDC_FINDTRAP                    1601
#define IDC_PICKPOCKET                  1602
#define IDC_LUCK                        1603
#define IDC_TRACKING                    1604
#define IDC_STR                         1605
#define IDC_MAGCOLD                     1606
#define IDC_INT                         1607
#define IDC_MAGFIRE                     1608
#define IDC_WIS                         1609
#define IDC_CON                         1610
#define IDC_DEX                         1611
#define IDC_STRBON                      1612
#define IDC_CHA                         1613
#define IDC_FATIGUE                     1614
#define IDC_INTOX                       1615
#define IDC_NUMATTACKS                  1616
#define IDC_AC                          1617
#define IDC_EFFAC                       1618
#define IDC_CRUSHING                    1619
#define IDC_MISSILE                     1620
#define IDC_SLASHING                    1621
#define IDC_PIERCING                    1622
#define IDC_DEATH                       1623
#define IDC_WANDS                       1624
#define IDC_POLYMORPH                   1625
#define IDC_BREATH                      1626
#define IDC_FIRE                        1627
#define IDC_ELECTRICITY                 1628
#define IDC_ACID                        1629
#define IDC_MAGIC                       1630
#define IDC_DEF1                        1631
#define IDC_DEF2                        1632
#define IDC_REPUTATION                  1633
#define IDC_DEF3                        1634
#define IDC_KIT                         1635
#define IDC_DEF4                        1636
#define IDC_SLOTPICKER                  1637
#define IDC_SOUNDREF                    1638
#define IDC_TAGGED                      1639
#define IDC_REF                         1640
#define IDC_SLOTSPIN                    1641
#define IDC_BUDDY                       1642
#define IDC_NOSTEAL                     1643
#define IDC_BROWSE                      1644
#define IDC_LARGE                       1645
#define IDC_BROWSE2                     1646
#define IDC_SMALL                       1647
#define IDC_BROWSE3                     1648
#define IDC_BROWSE4                     1649
#define IDC_BROWSE5                     1650
#define IDC_BROWSE6                     1651
#define IDC_BROWSE7                     1652
#define IDC_BROWSE8                     1653
#define IDC_BROWSE9                     1654
#define IDC_BROWSE10                    1655
#define IDC_BROWSE11                    1656
#define IDC_BROWSE12                    1657
#define IDC_DESCICON                    1658
#define IDC_V1                          1659
#define IDC_V11                         1660
#define IDC_V20                         1661
#define IDC_V90                         1662
#define IDC_V10                         1663
#define IDC_V22                         1664
#define IDC_V12                         1665
#define IDC_V91                         1666
#define IDC_MAXENTRANCE                 1667
#define IDC_MAXTRIGGER                  1668
#define IDC_TRIGGERPICKER               1669
#define IDC_SPAWNPICKER                 1670
#define IDC_MAXSPAWN                    1671
#define IDC_SPAWNNUMPICKER              1672
#define IDC_MAXCRE                      1673
#define IDC_ADDCRE                      1674
#define IDC_DELCRE                      1675
#define IDC_FREQUENCY                   1676
#define IDC_DELAY                       1677
#define IDC_UNKNOWN2                    1678
#define IDC_LOW                         1679
#define IDC_TRESET                      1680
#define IDC_UNKNOWN7C                   1681
#define IDC_TUNDET                      1682
#define IDC_UNKNOWN80                   1683
#define IDC_TDETECT                     1684
#define IDC_HIGH                        1685
#define IDC_TUNK1                       1686
#define IDC_UNKNOWN82                   1687
#define IDC_TUNK2                       1688
#define IDC_TNPC                        1689
#define IDC_TUNK3                       1690
#define IDC_NONPC                       1691
#define IDC_TDEACTIVATED                1692
#define IDC_TOVERRIDE                   1693
#define IDC_TDOOR                       1694
#define IDC_TUNK4                       1695
#define IDC_TUNK5                       1696
#define IDC_TUNK6                       1697
#define IDC_TUNK7                       1698
#define IDC_INFOSTR                     1699
#define IDC_MIN                         1700
#define IDC_MAX                         1701
#define IDC_FIELDS                      1702
#define IDC_UNKNOWN26                   1703
#define IDC_SONGS                       1704
#define IDC_AMBI1D                      1705
#define IDC_AMBI2D                      1706
#define IDC_AMBI1N                      1707
#define IDC_AMBI2N                      1708
#define IDC_AXE                         1709
#define IDC_INFOSTR2                    1710
#define IDC_MORNING                     1711
#define IDC_AFTERNOON                   1712
#define IDC_TIMEOFDAY                   1713
#define IDC_VOLUMEN                     1714
#define IDC_AMBIENTPICKER               1715
#define IDC_MAXAMBIENT                  1716
#define IDC_RADIUS                      1717
#define IDC_VOLUME                      1718
#define IDC_HEIGHT                      1719
#define IDC_HEIGHT2                     1720
#define IDC_WAVRES                      1721
#define IDC_ADDWAV                      1722
#define IDC_DELWAV                      1723
#define IDC_MAXWAV                      1724
#define IDC_NUM                         1725
#define IDC_GAP                         1726
#define IDC_SOUNDNUM                    1727
#define IDC_CLEAR                       1728
#define IDC_U90                         1729
#define IDC_SECTION                     1730
#define IDC_UNKNOWN9A                   1731
#define IDC_UNKNOWN9C                   1732
#define IDC_UNKNOWNA0                   1733
#define IDC_UNKNOWNA2                   1734
#define IDC_DVAR                        1735
#define IDC_DESTRUCTED                  1736
#define IDC_UNKNOWNAC                   1737
#define IDC_DEFAULT                     1738
#define IDC_DROPFRAME                   1739
#define IDC_SPEAR                       1740
#define IDC_BLUNT                       1741
#define IDC_SPIKED                      1742
#define IDC_DIALOG                      1743
#define IDC_EXTEFFREMOVE                1744
#define IDC_RACE2                       1745
#define IDC_EXTEFFCOPY                  1746
#define IDC_CONTAINERPICKER             1747
#define IDC_UNKNOWNAE                   1748
#define IDC_MAXCONTAINER                1749
#define IDC_TYPE                        1750
#define IDC_DIFF                        1751
#define IDC_MAXITEM                     1752
#define IDC_ITEMNUMPICKER               1753
#define IDC_VOLUMED                     1754
#define IDC_PROJFRAME                   1755
#define IDC_UNKNOWN20                   1756
#define IDC_CLASS                       1757
#define IDC_EXTEFFPASTE                 1758
#define IDC_CLASS2                      1759
#define IDC_PAR1                        1760
#define IDC_VARIABLEPICKER              1761
#define IDC_VARIABLEPICKER2             1762
#define IDC_NOTE                        1763
#define IDC_COLOR                       1764
#define IDC_UNKNOWNC                    1765
#define IDC_NOTEPICKER                  1766
#define IDC_MAXVARIABLE                 1767
#define IDC_MAXNOTE                     1768
#define IDC_SCRIPTNAME                  1769
#define IDC_SCRIPTNAME2                 1770
#define IDC_DOORPICKER                  1771
#define IDC_DELEXP                      1772
#define IDC_EXPLORED                    1773
#define IDC_OPEN                        1774
#define IDC_U54                         1775
#define IDC_DOORID                      1776
#define IDC_DURATION                    1777
#define IDC_TIMING                      1778
#define IDC_DIALOGTREE                  1779
#define IDC_OPTION                      1780
#define IDC_CONDITION                   1781
#define IDC_JOURNAL                     1782
#define IDC_ACTION                      1783
#define IDC_HASOPTION                   1784
#define IDC_HASCONDITION                1785
#define IDC_HASACTION                   1786
#define IDC_HASJOURNAL                  1787
#define IDC_JOURTYPE                    1788
#define IDC_LABEL                       1789
#define IDC_SOUND                       1790
#define IDC_NODE                        1791
#define IDC_TRAN                        1792
#define IDC_STATE                       1793
#define IDC_BOTH                        1794
#define IDC_BOTH2                       1795
#define IDC_TOP                         1796
#define IDC_IGNORECASE                  1797
#define IDC_STRING                      1798
#define IDC_INTERNAL                    1799
#define IDC_NEW                         1800
#define IDC_UNKNOWN01                   1801
#define IDC_UNKNOWN0E                   1802
#define IDC_BROWSE1                     1803
#define IDC_MAXACTOR                    1804
#define IDC_SPARKCOLOUR                 1805
#define IDC_X                           1807
#define IDC_MAXDOOR                     1808
#define IDC_Y                           1809
#define IDC_BROWSE13                    1810
#define IDC_Z                           1811
#define IDC_BROWSE14                    1812
#define IDC_EXTENSION                   1813
#define IDC_MPTRAVEL                    1814
#define IDC_MPSMOKE                     1815
#define IDC_AIM                         1816
#define IDC_SMOKETYPE                   1817
#define IDC_FREQ1                       1818
#define IDC_FREQ2                       1819
#define IDC_FREQ3                       1820
#define IDC_TRIGGER                     1821
#define IDC_CONESIZE                    1822
#define IDC_EXPLOSION                   1823
#define IDC_FRAGMENT                    1824
#define IDC_UNKNOWN14                   1825
#define IDC_PROJECTILE                  1826
#define IDC_NPCPICKER                   1827
#define IDC_FAMILIARPICKER              1828
#define IDC_FAMILIAR                    1829
#define IDC_ADDVAR                      1830
#define IDC_ADDVAR2                     1831
#define IDC_REMOVEVAR                   1832
#define IDC_REMOVEVAR2                  1833
#define IDC_ADDNPC                      1834
#define IDC_DELNPC                      1835
#define IDC_STARTAREA                   1836
#define IDC_GAMETIME                    1837
#define IDC_JOURNALPICKER               1838
#define IDC_REALTIME                    1838
#define IDC_ADDJOURNAL                  1839
#define IDC_DELJOURNAL                  1840
#define IDC_MODIFIED                    1841
#define IDC_CAPTION                     1842
#define IDC_CHAPTER                     1843
#define IDC_TIME                        1844
#define IDC_PARTYSIZE                   1845
#define IDC_MAPCOUNT                    1846
#define IDC_MAXMAP                      1847
#define IDC_MOS                         1848
#define IDC_ADDMAP                      1849
#define IDC_DELMAP                      1850
#define IDC_WIDTH                       1851
#define IDC_WIDTH2                      1852
#define IDC_UNKNOWN18                   1853
#define IDC_MAPICONS                    1854
#define IDC_AREAPICKER                  1855
#define IDC_NAME                        1856
#define IDC_MAPNUMBER                   1857
#define IDC_AREAFLAG                    1858
#define IDC_ICONIDX                     1859
#define IDC_ADDAREA                     1860
#define IDC_DELAREA                     1861
#define IDC_CAPTIONTEXT                 1862
#define IDC_NORTH                       1863
#define IDC_EAST                        1864
#define IDC_WEST                        1865
#define IDC_SOUTH                       1866
#define IDC_MAXAREA                     1867
#define IDC_LIMIT                       1868
#define IDC_SPELLNAME                   1869
#define IDC_TRANSPARENT                 1870
#define IDC_INVICON                     1871
#define IDC_LEVELSLOT                   1872
#define IDC_SPELLPICKER                 1873
#define IDC_MEMORISED                   1874
#define IDC_BOOKPICKER                  1875
#define IDC_SPECIFIC                    1876
#define IDC_PAR2                        1877
#define IDC_SPECIFIC2                   1878
#define IDC_LOC                         1879
#define IDC_GENDER                      1880
#define IDC_TARGET                      1881
#define IDC_GENDER2                     1882
#define IDC_ITEMINVICON                 1883
#define IDC_ALIGN                       1884
#define IDC_ALIGN2                      1885
#define IDC_WEIGHT                      1886
#define IDC_PRICE                       1887
#define IDC_USEDUP                      1888
#define IDC_ITEMEXCL                    1889
#define IDC_ADDSLOT                     1890
#define IDC_SPELLTYPE                   1891
#define IDC_MAXSPELL                    1892
#define IDC_DELSLOT                     1893
#define IDC_MAXSLOT                     1894
#define IDC_MEMORISE                    1895
#define IDC_SPELLTYPE2                  1896
#define IDC_FORGET                      1897
#define IDC_BOOK                        1898
#define IDC_BOOK2                       1899
#define IDC_LINKPICKER                  1900
#define IDC_DIRECTION                   1901
#define IDC_MAXDIR                      1902
#define IDC_AREALINK                    1903
#define IDC_ENTRANCE                    1904
#define IDC_DISTANCE                    1905
#define IDC_TOOLTIPREF                  1906
#define IDC_TOOLTIPTEXT                 1907
#define IDC_MAGICAL                     1908
#define IDC_MOVABLE                     1909
#define IDC_INVICON1                    1910
#define IDC_INVICON2                    1911
#define IDC_CHANCE                      1912
#define IDC_MAXLINK                     1913
#define IDC_DIALOGRES                   1914
#define IDC_XPLIST                      1915
#define IDC_COMMAND                     1916
#define IDC_PARAM                       1917
#define IDC_VIEW                        1918
#define IDC_BITMAP                      1919
#define IDC_DROP                        1920
#define IDC_2DA                         1921
#define IDC_ROW                         1922
#define IDC_COLUMN                      1923
#define IDC_COLUMN2                     1924
#define IDC_ROW2                        1925
#define IDC_DESCICON1                   1926
#define IDC_DESCICON2                   1927
#define IDC_DESCICON3                   1928
#define IDC_DESCICON4                   1929
#define IDC_SAME                        1930
#define IDC_RECYCLE                     1931
#define IDC_CURSED                      1932
#define IDC_PROFICIENCY                 1933
#define IDC_CRITICAL                    1934
#define IDC_ANIMATION                   1935
#define IDC_STOLEN                      1936
#define IDC_EVIL                        1937
#define IDC_EGNEUTRAL                   1938
#define IDC_TBG                         1939
#define IDC_OTHERMAX                    1940
#define IDC_OPENOTHER                   1941
#define IDC_TBGMAX                      1942
#define IDC_OPENTBG                     1943
#define IDC_FOUR                        1944
#define IDC_MAXANIM                     1945
#define IDC_ANIMPICKER                  1946
#define IDC_BMP                         1947
#define IDC_GOOD                        1948
#define IDC_LAWFUL                      1949
#define IDC_LCNEUTRAL                   1950
#define IDC_GREY                        1951
#define IDC_GLOW                        1952
#define IDC_TINT                        1953
#define IDC_CHAOTIC                     1954
#define IDC_BARD                        1955
#define IDC_CLERIC                      1956
#define IDC_CLMAGE                      1957
#define IDC_CLTHIEF                     1958
#define IDC_FICLERIC                    1959
#define IDC_FIGHTER                     1960
#define IDC_CLRANGER                    1961
#define IDC_FITHIEF                     1962
#define IDC_FIDRUID                     1963
#define IDC_FIMAGE                      1964
#define IDC_FIMACLERIC                  1965
#define IDC_FIMATHIEF                   1966
#define IDC_MAGE                        1967
#define IDC_MATHIEF                     1968
#define IDC_PALADIN                     1969
#define IDC_RANGER                      1970
#define IDC_THIEF                       1971
#define IDC_ELF                         1972
#define IDC_DWARF                       1973
#define IDC_HALF_ELF                    1974
#define IDC_HALFLING                    1975
#define IDC_HUMAN                       1976
#define IDC_GNOME                       1977
#define IDC_HALFORC                     1978
#define IDC_MONK                        1979
#define IDC_DRUID                       1980
#define IDC_TALOS                       1981
#define IDC_HELM                        1982
#define IDC_LATHANDER                   1983
#define IDC_TOTEMIC                     1984
#define IDC_SHAPE                       1985
#define IDC_AVENGER                     1986
#define IDC_BARBARIAN                   1987
#define IDC_WILDMAGE                    1988
#define IDC_STALKER                     1989
#define IDC_BEAST                       1990
#define IDC_ASSASSIN                    1991
#define IDC_BOUNTY                      1992
#define IDC_SWASH                       1993
#define IDC_BLADE                       1994
#define IDC_JESTER                      1995
#define IDC_SKALD                       1996
#define IDC_BAM                         1997
#define IDC_STACK                       1998
#define IDC_LORE                        1999
#define IDC_SEQ2                        2000
#define IDC_SPELLRES                    2001
#define IDC_REMALLITEM2                 2002
#define IDC_SPELLRES2                   2003
#define IDC_REMALLSPELL                 2004
#define IDC_UNLIMIT                     2005
#define IDC_REMALLDRINK                 2006
#define IDC_IDENTIFIED                  2007
#define IDC_AREA                        2008
#define IDC_PAGE                        2009
#define IDC_LIGHTNING                   2010
#define IDC_CRERES                      2011
#define IDC_AREATYPE                    2012
#define IDC_COPY                        2013
#define IDC_UNKNOWN52                   2014
#define IDC_PASTE                       2015
#define IDC_UNKNOWN90                   2016
#define IDC_COPY2                       2017
#define IDC_UNKNOWN8C                   2018
#define IDC_PASTE2                      2019
#define IDC_WEATHER                     2020
#define IDC_FOREST                      2021
#define IDC_EXTENDEDNIGHT               2022
#define IDC_DAYNIGHT                    2023
#define IDC_CITY                        2024
#define IDC_DUNGEON                     2025
#define IDC_CANREST                     2026
#define IDC_OUTDOOR                     2027
#define IDC_UNKFLAG                     2028
#define IDC_RAIN                        2029
#define IDC_U3C                         2030
#define IDC_FOG                         2031
#define IDC_TALKNUM                     2032
#define IDC_U3E                         2033
#define IDC_SNOW                        2034
#define IDC_BRIGHTEST                   2035
#define IDC_LOG                         2036
#define IDC_INDENT                      2037
#define IDC_DSIZE                       2038
#define IDC_RED2                        2039
#define IDC_DECOMPILED                  2040
#define IDC_LABEL3                      2042
#define IDC_TAG                         2043
#define IDC_REMBAF                      2044
#define IDC_CWDBAF                      2045
#define IDC_UNDROPPABLE                 2046
#define IDC_CHECK                       2047
#define IDC_DECOMPRESS                  2048
#define IDC_NOCHECK                     2049
#define IDC_DATAFOLDER                  2050
#define IDC_SCROLL3                     2051
#define IDC_MAP                         2052
#define IDC_SLIDERFRAME1                2053
#define IDC_SLIDERFRAME2                2054
#define IDC_EDITMOS1                    2055
#define IDC_SELECTED                    2056
#define IDC_BAMFRAME                    2057
#define IDC_METHOD                      2058
#define IDC_DROPCYC                     2059
#define IDC_MUS                         2060
#define IDC_SCROLL1                     2061
#define IDC_SCROLL2                     2062
#define IDC_STEREO                      2063
#define IDC_SORTEFFECT                  2064
#define IDC_EFFNUMBER                   2065
#define IDC_GRNDICON                    2066
#define IDC_EXPORT                      2067
#define IDC_IMPORT                      2068
#define IDC_TEXTAREA4                   2069
#define IDC_ADDFRAME                    2070
#define IDC_DELFRAME                    2071
#define IDC_NEWFRAME                    2072
#define IDC_NEWCYCLE                    2073
#define IDC_TEXT2                       2074
#define IDC_AMBINUMPICKER               2075
#define IDC_EDITLINK                    2076
#define IDC_PST                         2077
#define IDC_IDS                         2078
#define IDC_DELETE                      2079
#define IDC_EDIT                        2080
#define IDC_FROMSP                      2081
#define IDC_TOSP                        2082
#define IDC_MITEM                       2083
#define IDC_RED                         2084
#define IDC_MSTRREF                     2085
#define IDC_GREEN2                      2086
#define IDC_PALETTE                     2087
#define IDC_PLAYSOUND                   2088
#define IDC_NOCUT                       2089
#define IDC_CREATURENUM                 2090
#define IDC_CNT                         2091
#define IDC_BUTTONFLAG                  2092
#define IDC_READD                       2093
#define IDC_W98                         2094
#define IDC_ITMCOLOR                    2095
#define IDC_LIGHTMAP                    2096
#define IDC_SEARCHMAP                   2097
#define IDC_HEIGHTMAP                   2098
#define IDC_NOID                        2099
#define IDC_HEIGHTMAP2                  2099
#define IDC_FRAME2                      2100
#define IDC_SET                         2101
#define IDC_FIND                        2102
#define IDC_NEWRESOURCE                 2103
#define IDC_FIRST                       2104
#define IDC_SCREEN                      2105
#define IDC_OVERLAYPICKER               2106
#define IDC_OVERLAYNUM                  2107
#define IDC_DOORNUM                     2108
#define IDC_WALLGROUPNUM                2109
#define IDC_TILESET                     2110
#define IDC_DOORPOLYNUM                 2111
#define IDC_SET2                        2112
#define IDC_CLOSED                      2113
#define IDC_EDITMOS2                    2114
#define IDC_EDITMOS3                    2115
#define IDC_WALLGROUPPICKER             2116
#define IDC_SET3                        2117
#define IDC_DOORPOLYPICKER              2118
#define IDC_EDITDOORPOLY                2119
#define IDC_EDITWALLPOLY                2120
#define IDC_SEARCH                      2121
#define IDC_PLAYWHOLE                   2122
#define IDC_POLYGONTYPE                 2123
#define IDC_EATSPACE                    2124
#define IDC_DITHER                      2125
#define IDC_VERTEXPICKER                2126
#define IDC_SLIDERMOS                   2127
#define IDC_SLIDERBAM                   2128
#define IDC_SLIDERCYCLE                 2129
#define IDC_REVERSE                     2130
#define IDC_MINX                        2131
#define IDC_MINY                        2132
#define IDC_MAXX                        2133
#define IDC_MAXY                        2134
#define IDC_LABEL2                      2135
#define IDC_EDITLINK2                   2136
#define IDC_ADDALT                      2137
#define IDC_NODROP                      2138
#define IDC_WINDOWPICKER                2139
#define IDC_PROBLEM                     2140
#define IDC_HIDDEN                      2141
#define IDC_NOPC                        2142
#define IDC_SHIFT                       2143
#define IDC_RELOAD                      2144
#define IDC_TOB                         2145
#define IDC_SPIN                        2146
#define IDC_SLOT                        2147
#define IDC_ID                          2148
#define IDC_ID2                         2149
#define IDC_LENGTH                      2150
#define IDC_TEXTAREA2                   2151
#define IDC_TEXTAREA3                   2152
#define IDC_LABEL1                      2153
#define IDC_BUTTONBAM                   2154
#define IDC_BUTTONCYCLE                 2155
#define IDC_BUTTONFRAME1                2156
#define IDC_BUTTONFRAME2                2157
#define IDC_BUTTONFRAME3                2158
#define IDC_BUTTONFRAME4                2159
#define IDC_KEEN                        2160
#define IDC_MELEE                       2161
#define IDC_OUTFOLDER                   2162
#define IDC_OUTPUT                      2163
#define IDC_WEIDUSTR                    2164
#define IDC_DLTC                        2165
#define IDC_IDUSTR                      2166
#define IDC_TEXTAREA1                   2167
#define IDC_SOURCE                      2168
#define IDC_NEW1                        2169
#define IDC_NEW2                        2170
#define IDC_NEW3                        2171
#define IDC_NEW4                        2172
#define IDC_MUSDAY                      2173
#define IDC_MUSNIGHT                    2174
#define IDC_MUSWIN                      2175
#define IDC_MUSBATTLE                   2176
#define IDC_MUSLOSE                     2177
#define IDC_BOTTOM                      2178
#define IDC_DELCTRL                     2179
#define IDC_CONTROLPICKER               2180
#define IDC_ADDCTRL                     2181
#define IDC_SAVETIS                     2182
#define IDC_ADDWIN                      2183
#define IDC_DELWIN                      2184
#define IDC_EXTRACT                     2185
#define IDC_HORIZONTAL                  2186
#define IDC_VERTICAL                    2187
#define IDC_DAMAGEINC                   2188
#define IDC_PREVIEW                     2189
#define IDC_BIFLIST                     2190
#define IDC_DAMAGE                      2191
#define IDC_BIFPOS                      2192
#define IDC_FILEPOS                     2193
#define IDC_FILELIST                    2194
#define IDC_OCTREE                      2195
#define IDC_HALF                        2196
#define IDC_MINIMAP                     2197
#define IDC_DELETEALL                   2198
#define IDC_MARK                        2199
#define IDC_REMOVEBIF                   2200
#define IDC_CTRLCNT                     2201
#define IDC_PAR3                        2202
#define IDC_PAR4                        2203
#define IDC_LEVELINC                    2204
#define IDC_DODAMAGES                   2205
#define IDC_REVISION                    2206
#define IDC_DURATIONINC                 2207
#define IDC_DODURATIONS                 2208
#define IDC_SPINCURSOR                  2209
#define IDC_WINCNT                      2210
#define IDC_PWIDTH                      2211
#define IDC_PHEIGHT                     2212
#define IDC_FIT                         2213
#define IDC_LAUNCH                      2214
#define IDC_SPINY                       2215
#define IDC_SPINX                       2216
#define IDC_SETPOS                      2217
#define IDC_SETDEST                     2218
#define IDC_POS                         2219
#define IDC_RANGEINC                    2220
#define IDC_DORANGES                    2221
#define IDC_ALT                         2222
#define IDC_CENTER                      2223
#define IDC_EDITTILE                    2224
#define IDC_BLOCKPICKER                 2225
#define IDC_INIT                        2226
#define IDC_SHOWALL                     2227
#define IDC_SHOWGRID                    2228
#define IDC_NEXT                        2229
#define IDC_PREV                        2230
#define IDC_FILL                        2231
#define IDC_WEIDU                       2232
#define IDC_DOLEVELS                    2233
#define IDC_IDENTIFY                    2234
#define IDC_UNKNOWN94                   2235
#define IDC_LASTSAVED                   2236
#define IDC_ZIP                         2237
#define IDC_OVERLAY                     2238
#define IDC_FIXALTER                    2239
#define IDC_GREENWATER                  2240
#define IDC_TILEIDX                     2241
#define IDC_POS1                        2242
#define IDC_POS2                        2243
#define IDC_EDITBLOCK                   2244
#define IDC_STH1                        2245
#define IDC_EDITBLOCK2                  2245
#define IDC_STH2                        2246
#define IDC_STH3                        2247
#define IDC_STH4                        2248
#define IDC_STH5                        2249
#define IDC_USEBAM                      2250
#define IDC_MIRROR                      2251
#define IDC_MIRROR2                     2252
#define IDC_INSERT                      2253
#define IDC_EDITPOLYGON                 2254
#define IDC_MOVE                        2255
#define IDC_KILLXP                      2256
#define IDC_KILLNUM                     2257
#define IDC_KILLXP2                     2258
#define IDC_KILLNUM2                    2259
#define IDC_UNDO                        2260
#define IDC_IDSSPECIES                  2261
#define IDC_STEPS                       2262
#define IDC_RECHARGES                   2263
#define IDC_BLEND                       2264
#define IDC_SPECIAL                     2265
#define IDC_SWAP                        2266
#define IDC_TORMENT                     2267
#define IDC_MPVXP                       2268
#define IDC_MPVNAME                     2269
#define IDC_FEETCIRCLE                  2270
#define IDC_LOAD3                       2271
#define IDC_NIGHTMAP                    2272
#define IDC_EDITTILE2                   2273
#define IDC_CLEANUP                     2274
#define IDC_EMBED                       2275
#define IDC_U3A                         2276
#define IDC_STATIC2                     2277
#define IDC_STATIC3                     2278
#define IDC_STATIC4                     2279
#define IDC_STATIC5                     2280
#define IDC_STATIC6                     2281
#define IDC_SIZECHECK                   2282
#define IDC_WALL                        2283
#define IDC_INTDECOMP                   2284
#define IDC_VOICESET                    2285
#define IDC_INTCOMP                     2286
#define IDC_ITEM                        2287
#define IDC_SPELL                       2288
#define IDC_HAPPINESS                   2289
#define IDC_SPELL1                      2290
#define IDC_SPELL2                      2291
#define IDC_SPELL3                      2292
#define IDC_SPELL4                      2293
#define IDC_SPELL5                      2294
#define IDC_SPELL6                      2295
#define IDC_SPELL7                      2296
#define IDC_SPELL8                      2297
#define IDC_SPELL9                      2298
#define IDC_UNKNOWN56                   2299
#define IDC_SLIDER                      2300
#define IDC_EDIT2                       2301
#define IDC_FORCENEW                    2302
#define IDC_CD                          2303
#define IDC_ZOOM                        2304
#define IDC_SUBRACE                     2305
#define IDC_SKILL                       2312
#define IDC_SKILLPICKER                 2313
#define IDC_ANIMLIST                    2319
#define IDC_FILTER                      2320
#define IDC_SHADOW                      2322
#define IDC_BREAKABLE                   2331
#define IDC_BUTTON1                     2333
#define IDC_TOTAL                       2336
#define IDC_MEMORISED2                  2337
#define IDC_STATIC1                     2338
#define IDC_PROJPICKER                  2340
#define IDC_DAYMOVIE                    2342
#define IDC_NIGHTMOVIE                  2343
#define ID_RESCAN                       32771
#define ID_RESCAN2                      32772
#define ID_EDIT_ITEM                    32773
#define ID_CHECK_ITEM                   32774
#define ID_EDIT_SPELL                   32775
#define ID_CHECK_SPELL                  32776
#define ID_EDIT_STORE                   32777
#define ID_CHECK_STORE                  32778
#define ID_EDIT_PROJECTILE              32779
#define ID_CHECK_PROJECTILE             32780
#define ID_EDIT_EFFECT                  32781
#define ID_TOOLTIPS                     32782
#define ID_EDIT_CREATURE                32783
#define ID_CHECK_EFFECT                 32784
#define ID_CHECK_CREATURE               32785
#define ID_LOGGING_NONE                 32787
#define ID_LOGGING_SCREEN               32788
#define ID_LOGGING_FILE                 32789
#define ID_PROGRESS                     32790
#define ID_SAVESETTINGS                 32791
#define ID_EDIT_VVC                     32792
#define ID_CHECK_VVC                    32793
#define ID_FILE_EXTRACT                 32794
#define ID_SEARCH_ITEM                  32795
#define ID_SEARCH_SPELL                 32796
#define ID_SEARCH_STORE                 32797
#define ID_SEARCH_PROJECTILE            32798
#define ID_SEARCH_EFFECT                32799
#define ID_SEARCH_CREATURE              32800
#define ID_SEARCH_VVC                   32801
#define ID_READONLY                     32802
#define ID_ADDCFBTOSPELLS               32803
#define ID_CLEARCFBFROMSPELLS           32804
#define ID_SCANVARIABLES                32805
#define ID_CHECK_SCRIPT                 32806
#define ID_SEARCH_SCRIPT                32807
#define ID_EDIT_SCRIPT                  32808
#define ID_RESCAN3                      32809
#define ID_SEARCH_AREA                  32810
#define ID_CHECK_AREA                   32811
#define ID_EDIT_AREA                    32812
#define ID_CHECK_DIALOG                 32813
#define ID_SEARCH_DIALOG                32814
#define ID_EDIT_DIALOG                  32815
#define ID_EDIT_VARIABLES               32816
#define ID_FILE_BUILDBIF                32819
#define ID_COMPAT                       32820
#define ID_EDIT_ANIMATION               32823
#define ID_CHECK_ANIMATION              32824
#define ID_FILE_LOADBAM                 32825
#define ID_FILE_LOADEXTERNALBAM         32826
#define ID_FILE_SAVEBAMAS               32827
#define ID_ANIMATECYCLE                 32828
#define ID_SAVEPALETTE                  32829
#define ID_LOADPALETTE                  32830
#define ID_EDITPALETTE                  32831
#define ID_COLORSCALE                   32832
#define ID_FORCEPALETTE                 32833
#define ID_UNCOMPRESSBIF                32834
#define ID_ORDERPALETTE                 32835
#define ID_TRIMPALETTE                  32836
#define ID_FILE_SEARCH                  32837
#define ID_WAVCTOWAV                    32838
#define ID_COLORSCALE2                  32839
#define ID_REVERSECYCLE                 32840
#define ID_RESCAN4                      32841
#define ID_REFRESH                      32852
#define ID_EXPAND                       32853
#define ID_COLLAPSE                     32854
#define ID_SEARCHNODE                   32855
#define ID_FOLLOWLINK                   32856
#define ID_REMOVE                       32857
#define ID_ADDNODE                      32859
#define ID_CONVERT                      32860
#define ID_SWAPNODES                    32861
#define ID_EDIT_GAMES                   32862
#define ID_CHECK_GAME                   32863
#define ID_INCREASEWEIGHT               32864
#define ID_TOOLSORDER                   32865
#define ID_TOOLSORDER2                  32866
#define ID_EDIT_WORLDMAP                32867
#define ID_ADDTOP                       32868
#define ID_EDIT_GRAPHICS                32869
#define ID_CHECK_WORLDMAP               32870
#define ID_EXPORT_WEIDU                 32871
#define ID_EXPORT_TBG                   32872
#define ID_IMPORT_WEIDU                 32873
#define ID_FILE_SAVEAS                  32876
#define ID_FILE_LOAD                    32877
#define ID_EDIT_2DA                     32878
#define ID_RESCAN5                      32879
#define ID_EDIT_IDS                     32880
#define ID_FILE_IMPORTTBG               32881
#define ID_FILE_EXPORTTBG               32882
#define ID_FILE_LOADEXTERNALSCRIPT      32885
#define ID_FILE_LOADSOURCE              32886
#define ID_FILE_SAVECOMPILESCRIPT       32887
#define ID_FILE_SAVESCRIPT              32888
#define ID_CHECK                        32894
#define ID_FILE_SAVEBAM                 32897
#define ID_FILE_TBG                     32898
#define ID_CHECK_2DA                    32899
#define ID_TOOLS_LOOKUPSTRREF           32900
#define ID_UNCOMPRESSSAV                32901
#define ID_UNCOMPRESSCBF                32902
#define ID_ACMTOWAV                     32903
#define ID_EDIT_MUSICLIST               32904
#define ID_WAVTOACM                     32905
#define ID_WAVTOWAVC                    32906
#define ID_TOOLSPST                     32907
#define ID_EDIT_TILESET                 32908
#define ID_UNUSEDLINKS                  32909
#define ID_ADDCFB                       32910
#define ID_REMOVECFB                    32911
#define ID_SEARCH                       32912
#define ID_ACMTOWAV2                    32914
#define ID_WAVCTOWAV2                   32915
#define ID_TRIM                         32923
#define ID_CLEAR                        32924
#define ID_CHECKSOUND                   32925
#define ID_CHECKTAG                     32926
#define ID_FILE_IMPORTD                 32927
#define ID_EXPORTSOUNDSET               32928
#define ID_IMPORTSOUNDSET               32929
#define ID_EDIT_KEY                     32930
#define ID_REORDERBIF                   32931
#define ID_SEARCH_2DA                   32932
#define ID_OPTIONS_AUTOCHECK            32933
#define ID_OPTIONS_LARGEINDENT          32934
#define ID_EDIT_SELECTALL               32938
#define ID_EDIT_DELETE                  32942
#define ID_ADD                          32943
#define ID_ORDER                        32945
#define ID_INT                          32948
#define ID_FOUR                         32949
#define ID_PLAY_PLAYWHOLE               32950
#define ID_PLAY_PLAYPART                32951
#define ID_PALETTE_EDIT                 32952
#define ID_PALETTE_TRIM                 32953
#define ID_TOOLS_EXTRACTTILES           32954
#define ID_CONTINUOUSPLAY               32955
#define ID_CLEANUP                      32956
#define ID_CYCLE_SETCYCLE               32957
#define ID_CYCLE_REMOVECYCLE            32958
#define ID_CYCLE_INSERTCYCLE            32959
#define ID_CYCLE_ADDCYCLE               32960
#define ID_EDIT_ADDFRAME                32961
#define ID_EDIT_DROPFRAME               32962
#define ID_EDIT_IMPORTFRAME             32964
#define ID_CYCLE_DROPFRAME              32966
#define ID_TOOLS_CENTERFRAMES           32967
#define ID_FRAME_CENTERFRAME            32968
#define ID_FILE_LOADEXTERNALBMP         32969
#define ID_TOOLS_IMPORTFRAMES           32970
#define ID_TOOLS_COMPRESSALLFRAMES      32971
#define ID_TOOLS_DECOMPRESSALLFRAMES    32972
#define ID_TOOLS_ALIGNALL               32973
#define ID_TOOLS_IDSBROWSER             32974
#define ID_SAVECFB                      32976
#define ID_SEARCH_BAM                   32977
#define ID_EDIT_CHUI                    32978
#define ID_FILE_LOADEXTERNAL            32979
#define ID_SEARCH_UI                    32980
#define ID_CHECK_UI                     32981
#define ID_TOOLS_MIRRORAREAVERTICALLY   32982
#define ID_TOOLS_DURATION               32983
#define ID_CYCLE_COPYCYCLE              32984
#define ID_CYCLE_PASTECYCLE             32985
#define ID_EDIT_STRINGSSRC              32986
#define ID_TOOLS_SCANJOURNALENTRIES     32987
#define ID_TOOLS_CAPITALIZEENTRIES      32988
#define ID_REPAIRWED                    32989
#define ID_REPAIRWED2                   32990
#define ID_AVATARS                      32992
#define ID_SHIFT_FORWARD                32993
#define ID_SHIFT_BACKWARD               32994
#define ID_COMPRESSBIF                  32997
#define ID_COMPRESSCBF                  32998
#define ID_TISPACK                      32999
#define ID_FILE_LOADBMP                 33000
#define ID_FILE_MERGEBAM                33002
#define ID_FILE_MERGEEXTERNALBAM        33003
#define ID_HELP_README                  33014
#define ID_FLIPCYCLE                    33015
#define ID_FLIPFRAME                    33016
#define ID_CREATEMIRROR                 33017
#define ID_TOOLS_DROPALLBUTLAST         33018
#define ID_REDUCEORIENTATION            33019
#define ID_MERGEBAM                     33020
#define ID_SKIMSAV                      33021
#define ID_OPTIONS_SWITCHTOSHORTHAND    33022
#define ID_OPTIONS_TREEEDIT             33023
#define ID_FILE_EXPORTUSINGSHORTHAND    33024
#define ID_FILE_IMPORTSHORTHAND         33025
#define ID_CYCLE_ALIGNFRAMES            33026
#define ID_USEDIALOGF                   33027
#define ID_CYCLE_DROPFRAME10            33028
#define ID_TOOLS_GUESSDIMENSIONS        33029
#define ID_TOOLS_EXPLODE                33030
#define ID_TOOLS_IMPLODE                33031
#define ID_RELOAD                       33032
#define ID_TOOLS_SYNCHRONISETLKS        33033
#define ID_TOOLS_ADDSPARKDATA           33034
#define ID_TOOLS_DECOMPILE              33035
#define ID_TOOLS_MINIMALFRAME           33036
#define ID_FRAME_MINIMIZEFRAME          33037
#define ID_EDIT_FINDID                  33038
#define ID_TOOLS_SPLITFRAMES            33039
#define ID_OPTIONS_USEINTERNALDECOMPILER 33040
#define ID_OPTIONS_USEINTERNALCOMPILER  33041
#define ID_OPTIONS_LOGGING              33042
#define ID_FILE_TP2                     33043
#define ID_EXTRACTION_RECOMPRESSSAV     33044
#define ID_TOOLS_PLAYSOUND              33045
#define ID_CHECK_AVATAR2DA              33046
#define ID_CHECK_SPAWNINI               33047
#define ID_SEARCH_BMP                   33048
#define ID_CONTEXT                      0xF180

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        233
#define _APS_NEXT_COMMAND_VALUE         33049
#define _APS_NEXT_CONTROL_VALUE         2352
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
